version: "3"

services:

  server:
    image: nginx
    container_name: nginx
    ports:
      - 8010:80

  backend:
    build: docker/web
    container_name: web
    ports:
      - 8000:8000
    volumes:
      - .:/app

  db:
    image: mysql:5.7
    container_name: pdf.db
    hostname: pdf.db
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: pdf
    ports:
      - 3306:3306
#
#  phpmyadmin:
#    container_name: php-myadmin
#    depends_on:
#      - db
#    image: phpmyadmin/phpmyadmin
#    ports:
#      - 8080:80
#    environment:
#      PMA_HOST: db
#      MYSQL_ROOT_PASSWORD: 1
